import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // Main documentation sidebar
  tutorialSidebar: [
    'index',
    'for-tool-providers',
    {
      type: 'category',
      label: 'Communication Protocols',
      items: [
        'protocols/index',
        'protocols/http',
        'protocols/websocket',
        'protocols/sse',
        'protocols/cli',
        'protocols/text',
        'protocols/mcp',
      ],
    },
    'implementation',
    'security',
    'utcp-vs-mcp',
    'migration-v0.1-to-v1.0',
    {
      type: 'category',
      label: 'API Reference',
      items: [
        'api/index',
        {
          type: 'category',
          label: 'Core',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/core',
            },
          ],
        },
        {
          type: 'category',
          label: 'Plugins',
          items: [
            {
              type: 'autogenerated',
              dirName: 'api/plugins',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;
