export const PROVIDER_TYPE_ICONS: Record<string, string> = {
  'http': '🌐',
  'websocket': '🔌',
  'grpc': '⚡',
  'tcp': '🔗',
  'udp': '📡',
  'text': '📄',
  'cli': '💻',
  'graphql': '🎯',
  'sse': '📈',
  'webrtc': '📹'
};

export const CATEGORY_ICONS: Record<string, string> = {
  'Animals': '🐾',
  'Anime': '🎌',
  'Anti-Malware': '🛡️',
  'Art & Design': '🎨',
  'Authentication & Authorization': '🔐',
  'Blockchain': '⛓️',
  'Books': '📚',
  'Books & Literature': '📚',
  'Business': '💼',
  'Calendar': '📅',
  'Cloud Storage & File Sharing': '☁️',
  'Continuous Integration': '🔄',
  'Cryptocurrency': '₿',
  'Currency Exchange': '💱',
  'Data Validation': '✅',
  'Development': '⚙️',
  'Development & Version Control': '⚙️',
  'Dictionaries': '📖',
  'Documents & Productivity': '📄',
  'Email': '📧',
  'Entertainment': '🎭',
  'Environment': '🌍',
  'Events': '📌',
  'Finance': '💰',
  'Food & Drink': '🍕',
  'Games & Comics': '🎮',
  'Gaming & Entertainment': '🎮',
  'Geocoding': '🗺️',
  'Government': '🏛️',
  'Health': '🏥',
  'Jobs': '💼',
  'Machine Learning': '🤖',
  'Music': '🎵',
  'News': '📰',
  'News & Media': '📰',
  'Open Data': '📊',
  'Open Source Projects': '🔓',
  'Patent': '📋',
  'Payments & Finance': '💳',
  'Personality': '👤',
  'Phone': '📞',
  'Photography': '📸',
  'Programming': '💻',
  'Science & Math': '🔬',
  'Security': '🔒',
  'Shopping': '🛒',
  'Social': '👥',
  'Sports & Fitness': '⚽',
  'Test Data': '🧪',
  'Text Analysis': '📝',
  'Tracking': '📍',
  'Transportation': '🚗',
  'URL Shorteners': '🔗',
  'Vehicle': '🚙',
  'Video': '🎬',
  'Weather': '🌤️',
  'Weather & Climate': '🌤️',
  'AI & ML': '🤖',
  'AI & Machine Learning': '🤖'
};

export const DEFAULT_PROVIDER_ICON = '🔧';
export const DEFAULT_CATEGORY_ICON = '📦';