export const UI_CONSTANTS = {
  DESCRIPTION_LIMIT: 150,
  DESCRIPTION_MAX_LIMIT: 300,
  COPY_SUCCESS_TIMEOUT: 2000,
  DEFAULT_CATEGORY: 'Other',
  NO_DESCRIPTION_TEXT: 'No description available'
} as const;